### ISSUE TITLE
loading template using fpdi

### ISSUE THREAD

**Issue by mephic** [fpdf-easytable/fpdf-easytable#2]
am trying  to load a custom template using fpdi, am stuck. the page loads without error but with no template. kindly assist.

class PDF extends FPDI
{
    protected $_tplIdx;

    public function Header()
    {
        if (null === $this->_tplIdx) {
            $this->setSourceFile('templ/trans.pdf');
            $this->_tplIdx = $this->importPage(1);
        }

        $this->useTemplate($this->_tplIdx);
    }
}

$pdf = new PDF();

$pdf=new exFPDF('P','mm','A4');
$pdf->AddPage();
$pdf->SetMargins(20, 25, 30);

**Comment by fpdf-easytable** [comment]
Hi, this is how you should do it: assuming that fpdf.php, easyTable.php, exfpdf.php, fpdi.php and any other files from this libraries are in the same directory. So the class exfpdf should extends fpdi:

In exfpdf.php:

`<?php
// include 'fpdf.php'; <-- no needed here
 include 'fpdi.php';

 class exFPDF extends FPDI
 {
etc
etc
`
and in your project:

`<?php
include 'fpdf.php';
//include 'fpdi.php';  no needed because exfpdf is extending fpdi class
include 'exfpdf.php';
include 'easyTable.php';

 //$pdf = new FPDI();  remember exfpdf is extending the fpdi class 
 $pdf=new exFPDF(); // so we initiate exFPDF instead of FPDI

// add a page
$pdf->AddPage();
// set the source file
$pdf->setSourceFile("example-2.pdf");
// import page 1
$tplIdx = $pdf->importPage(1);
// use the imported page and place it at point 10,10 with a width of 100 mm
$pdf->useTemplate($tplIdx, 10, 10, 100);

//add another page
 $pdf->AddPage(); 
 $pdf->SetFont('helvetica','',10);

 $table1=new easyTable($pdf, 2);
 $table1->easyCell('Sales Invoice', 'font-size:30; font-style:B; font-color:#00bfff;');
 $table1->easyCell('', 'img:fpdf.png, w80; align:R;');
 $table1->printRow();
//etc
//etc
`
