### ISSUE TITLE
Feature request: improved spliting rows between pages

### ISSUE THREAD

**Issue by badochov** [fpdf-easytable/fpdf-easytable#6]
Could you please add feature that will make it possible to split rows between pages so that the row isn't cut in half when it overlap to next page but is whole on next page?

**Comment by fpdf-easytable** [comment]
I do not get what you are trying to say because it seems that you want that the row splits between pages ("... it possible to split rows between pages...") then you do not want that the rows splits in half ("... so that the row isn't cut in half...") what about if it cuts in 3/4, would it be better? (sorry I couldn't resist the sarcastic comment :-D ) Seriously, check the documentation for the property split-row. By default any row that does not fit in the page is printed in the next page. If you want that the row splits (cuts) between two pages set split-row:true in the css for the table not for the row, again read the documentation.
